
-- MySQL Script generated by MySQL Workbench
-- sáb 02 jun 2018 19:36:56 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TPDW2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TPDW2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TPDW2` DEFAULT CHARACTER SET utf8 ;
USE `TPDW2` ;

-- -----------------------------------------------------
-- Table `TPDW2`.`DimTempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPDW2`.`DimTempo` (
  `idTempo` INT NOT NULL,
  `ano` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTempo`));


-- -----------------------------------------------------
-- Table `TPDW2`.`DimLocalizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPDW2`.`DimLocalizacao` (
  `idLocalizacao` INT NOT NULL,
  `continente` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocalizacao`));


-- -----------------------------------------------------
-- Table `TPDW2`.`DimEclipse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPDW2`.`DimEclipse` (
  `idEclipse` INT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEclipse`));


-- -----------------------------------------------------
-- Table `TPDW2`.`FatoFelicidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TPDW2`.`FatoFelicidade` (
  `idTempo` INT NOT NULL,
  `idLocalizacao` INT NOT NULL,
  `idEclipse` INT NOT NULL,
  `idFelicidade` INT NOT NULL,
  `familia` VARCHAR(45) NULL,
  `expectativaVida` DOUBLE NULL,
  `liberdade` DOUBLE NULL,
  `generorisade` DOUBLE NULL,
  `confiancaGoverno` DOUBLE NULL,
  `indiceDeFelicidade` DOUBLE NULL,
  `numeroMeteoros` INT NULL,
  PRIMARY KEY (`idTempo`, `idLocalizacao`, `idEclipse`, `idFelicidade`),
  INDEX `fk_Fato_DimTempo_idx` (`idTempo` ASC),
  INDEX `fk_Fato_DimLocalizacao1_idx` (`idLocalizacao` ASC),
  INDEX `fk_Fato_DimEclipse1_idx` (`idEclipse` ASC),
  CONSTRAINT `fk_Fato_DimTempo`
    FOREIGN KEY (`idTempo`)
    REFERENCES `TPDW2`.`DimTempo` (`idTempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_DimLocalizacao1`
    FOREIGN KEY (`idLocalizacao`)
    REFERENCES `TPDW2`.`DimLocalizacao` (`idLocalizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_DimEclipse1`
    FOREIGN KEY (`idEclipse`)
    REFERENCES `TPDW2`.`DimEclipse` (`idEclipse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
