-- solar
CatalogNumber VARCHAR(50),
CalendarDate VARCHAR(50),
continent VARCHAR(50),
country VARCHAR(50),
EclipseTime VARCHAR(50),
DeltaTs VARCHAR(50),
LunationNumber VARCHAR(50),
SarosNumber VARCHAR(50),
EclipseType VARCHAR(50),
Gamma VARCHAR(50),
EclipseMagnitude VARCHAR(50),
Latitude VARCHAR(50),
Longitude VARCHAR(50),
SunAltitude VARCHAR(50),
SunAzimuthPath VARCHAR(50),
Widthkm VARCHAR(50),
CentralDuration VARCHAR(50),

-- lunar
CatalogNumber VARCHAR(50),
CalendarDate VARCHAR(50),
continent VARCHAR(50),
country VARCHAR(50),
EclipseTime VARCHAR(50),
DeltaTs VARCHAR(50),
LunationNumber VARCHAR(50),
SarosNumber VARCHAR(50),
EclipseType VARCHAR(50),
QuincenaSolarEclipse VARCHAR(50),
Gamma VARCHAR(50),
PenumbralMagnitude VARCHAR(50),
UmbralMagnitude VARCHAR(50),
Latitude VARCHAR(50),
Longitude VARCHAR(50),
PenumbralEclipseDurationm VARCHAR(50),
PartialEclipseDurationm VARCHAR(50),
TotalEclipseDurationm VARCHAR(50),

-- meteorites
name VARCHAR(50),
id VARCHAR(50),
continent VARCHAR(50),
country VARCHAR(50),
nametype VARCHAR(50),
recclass VARCHAR(50),
mass VARCHAR(50),
fall VARCHAR(50),
year VARCHAR(50),
reclat VARCHAR(50),
reclong VARCHAR(50),
GeoLocation VARCHAR(50),


--reports
Country VARCHAR(50), 
HappinessRank VARCHAR(50), 
HappinessScore VARCHAR(50), 
Whiskerhigh VARCHAR(50), 
Whiskerlow VARCHAR(50), 
EconomyPerCapita VARCHAR(50), 
Family VARCHAR(50), 
HealthLifeExpectancy VARCHAR(50), 
Freedom VARCHAR(50), 
Generosity VARCHAR(50), 
TrustGovernmentCorruption VARCHAR(50), 
DystopiaResidual VARCHAR(50), 

